[project]
name = "fastapi-env"
version = "0.1.0"
description = "API de inferencia de pingüinos"
requires-python = ">=3.10"

dependencies = [
  "fastapi",
  "uvicorn",
  "numpy",
  "pandas",
  "scikit-learn",
  "joblib",
]

[tool.uv]
