FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl

WORKDIR /home/app

# Copia el archivo de requerimientos e instala las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código de la API (incluyendo el app.py que utiliza MLflow)
COPY . .

EXPOSE 8000

# Ejecuta Uvicorn para levantar el servicio FastAPI en el puerto 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
